serverInfo:
  name: "Aces BTC-ARK Channel Service"
  description: "ACES BTC to ARK Channel service for transferring BTC to ARK"
  instructions: >
    After this contract is executed, any BTC sent to depositBtcAddress will be exchanged for ARK and 
    sent directly to the given recipientArkAddress less service fees.
  version: "1.0.0"
  websiteUrl: "https://arkaces.com"
  inputSchema: >
    {
      "type": "object",
      "properties": {
        "recipientArkAddress": {
          "type": "string"
        }
      },
      "required": [
        "recipientArkAddress"
      ]
    }
  outputSchema: >
    {
      "type": "object",
      "properties": {
        "depositBtcAddress": {
          "type": "string"
        },
        "recipientArkAddress": {
          "type": "string"
        },
        "transfers": {
          "type": "array",
          "properties": {
            "btcAmount": {
              "type": "string"
            },
            "btcToArkRate": {
              "type": "string"
            },
            "btcFlatFee": {
              "type": "string"
            },
            "btcPercentFee": {
              "type": "string"
            },
            "btcTotalFee": {
              "type": "string"
            },
            "arkSendAmount": {
              "type": "string"
            },
            "arkTransactionId": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            }
          }
        }
      }
    }

#spring:
#  datasource:
#    url: "jdbc:h2:/tmp/btc_ark_channel_service.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
#    driver-class-name: "org.h2.Driver"
#  jpa:
#    hibernate:
#      ddl-auto: "create-drop"
#
#spring:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/btc_ark_channel_service_db
#    username: btc_ark_channel_service_db_user
#    password: btc_ark_channel_service_db_password

# Ark network config YML that listening will be performed against
arkNetworkConfigPath: "ark_network_config/testnet.yml"

server:
  port: 9190
