serverInfo:
  name: "Aces ARK-ETH Channel Service"
  description: "ACES ARK-ETH Channel service for transferring ARK to ETH"
  instructions: >
    After this contract is executed, any ARK sent to depositArkAddress will be exchanged for ETH and
    sent directly to the given recipientEthAddress less service fees.
  version: "1.0.0"
  websiteUrl: "https://arkaces.com"
  flatFee: "0"
  percentFee: "1.00%"
  inputSchema: >
    {
      "type": "object",
      "properties": {
        "recipientEthAddress": {
          "type": "string",
          "title": "Recipient ETH Address",
          "description": "Enter the ETH address to receive transfers."
        }
      },
      "required": [
        "recipientEthAddress"
      ]
    }
  outputSchema: >
    {
      "type": "object",
      "properties": {
        "depositArkAddress": {
          "type": "string"
        },
        "recipientEthAddress": {
          "type": "string"
        },
        "transfers": {
          "type": "array",
          "properties": {
            "id": {
              "type": "string"
            },
            "arkTransactionId": {
              "type": "string"
            },
            "arkAmount": {
              "type": "string"
            },
            "arkToEthRate": {
              "type": "string"
            },
            "arkFlatFee": {
              "type": "string"
            },
            "arkPercentFee": {
              "type": "string"
            },
            "arkTotalFee": {
              "type": "string"
            },
            "ethTransactionId": {
              "type": "string"
            },
            "ethSendAmount": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            }
          }
        }
      }
    }

#spring:
#  datasource:
#    driver-class-name: "org.h2.Driver"
#    url: "jdbc:h2:~/tmp/ark_eth_channel_service.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
#  database:
#    hibernate:
#      ddl-auto: "validate"
#  jpa:
#      database-platform: org.hibernate.dialect.H2Dialect

#spring:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/aces_ark_eth_channel_db
#    username: service_user
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: validate
#
#flyway:
#  enabled: true

arkNetworkConfigPath: "ark_network_config/testnet.yml"

serviceEthAccount:
  address: "change-me"

fees:
  arkFlatFee: 0
  arkPercentFee: 1

server:
  port: 9190

arkListener:
  url: "https://ark-listener-mainnet.arkaces.com/"

arkEventCallbackUrl: "http://localhost:9190/arkEvents"

arkMinConfirmations: 5

ethRpcRootUri: "http://127.0.0.1:8545"
